apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-deployment
    spec:
      volumes:
      - name: www-content
        emptyDir: {}
      containers:
        - name: hello-world
          image: helloworld-webserver:1.0.0
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
          - mountPath: /www
            name: state-volume
        - name: get-content-sidecar
          image: helloworld-webserver:1.0.0
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
          - mountPath: /www
            name: state-volume
