apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-deployment-1
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-deployment-1
    spec:
      containers:
        - name: hello-world
          image: helloworld-webserver:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
